---
# tasks file for node-pm2
- name: install nodejs
  become_user: "ec2-user"
  become: yes
  shell: "{{ item.cmd }}"
  with_items:
    - cmd: curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
    - cmd: sudo yum install -y nodejs

- name: Install pm2
  npm:
    name: pm2
    state: latest
    global: yes
